//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace osVodigiPlayer.osVodigiWS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://tempuri.org/")]
    public partial class Account : object
    {
        
        private int AccountIDField;
        
        private string AccountNameField;
        
        private string AccountDescriptionField;
        
        private string FTPServerField;
        
        private string FTPUsernameField;
        
        private string FTPPasswordField;
        
        private bool IsActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountName
        {
            get
            {
                return this.AccountNameField;
            }
            set
            {
                this.AccountNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountDescription
        {
            get
            {
                return this.AccountDescriptionField;
            }
            set
            {
                this.AccountDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FTPServer
        {
            get
            {
                return this.FTPServerField;
            }
            set
            {
                this.FTPServerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FTPUsername
        {
            get
            {
                return this.FTPUsernameField;
            }
            set
            {
                this.FTPUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FTPPassword
        {
            get
            {
                return this.FTPPasswordField;
            }
            set
            {
                this.FTPPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseVersion", Namespace="http://tempuri.org/")]
    public partial class DatabaseVersion : object
    {
        
        private string VersionField;
        
        private System.DateTime DateInstalledField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime DateInstalled
        {
            get
            {
                return this.DateInstalledField;
            }
            set
            {
                this.DateInstalledField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://tempuri.org/")]
    public partial class Player : object
    {
        
        private int PlayerIDField;
        
        private int AccountIDField;
        
        private int PlayerGroupIDField;
        
        private string PlayerNameField;
        
        private string PlayerLocationField;
        
        private string PlayerDescriptionField;
        
        private bool IsActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PlayerID
        {
            get
            {
                return this.PlayerIDField;
            }
            set
            {
                this.PlayerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PlayerGroupID
        {
            get
            {
                return this.PlayerGroupIDField;
            }
            set
            {
                this.PlayerGroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PlayerName
        {
            get
            {
                return this.PlayerNameField;
            }
            set
            {
                this.PlayerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PlayerLocation
        {
            get
            {
                return this.PlayerLocationField;
            }
            set
            {
                this.PlayerLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PlayerDescription
        {
            get
            {
                return this.PlayerDescriptionField;
            }
            set
            {
                this.PlayerDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="http://tempuri.org/")]
    public partial class UserAccount : object
    {
        
        private int UserIDField;
        
        private int AccountIDField;
        
        private string UsernameField;
        
        private string PasswordField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string EmailAddressField;
        
        private bool IsAdminField;
        
        private bool UserIsActiveField;
        
        private string AccountNameField;
        
        private string AccountDescriptionField;
        
        private string FTPServerField;
        
        private string FTPUsernameField;
        
        private string FTPPasswordField;
        
        private bool AccountIsActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool IsAdmin
        {
            get
            {
                return this.IsAdminField;
            }
            set
            {
                this.IsAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool UserIsActive
        {
            get
            {
                return this.UserIsActiveField;
            }
            set
            {
                this.UserIsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string AccountName
        {
            get
            {
                return this.AccountNameField;
            }
            set
            {
                this.AccountNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string AccountDescription
        {
            get
            {
                return this.AccountDescriptionField;
            }
            set
            {
                this.AccountDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string FTPServer
        {
            get
            {
                return this.FTPServerField;
            }
            set
            {
                this.FTPServerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string FTPUsername
        {
            get
            {
                return this.FTPUsernameField;
            }
            set
            {
                this.FTPUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string FTPPassword
        {
            get
            {
                return this.FTPPasswordField;
            }
            set
            {
                this.FTPPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool AccountIsActive
        {
            get
            {
                return this.AccountIsActiveField;
            }
            set
            {
                this.AccountIsActiveField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="osVodigiPlayer.osVodigiWS.osVodigiServiceSoap")]
    public interface osVodigiServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account_GetByName", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.Account_GetByNameResponse> Account_GetByNameAsync(osVodigiPlayer.osVodigiWS.Account_GetByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActivityLog_Create", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.ActivityLog_CreateResponse> ActivityLog_CreateAsync(osVodigiPlayer.osVodigiWS.ActivityLog_CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnsweredSurvey_Create", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AnsweredSurvey_CreateAsync(int accountid, int surveyid, int playerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnsweredSurveyQuestionOption_Create", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AnsweredSurveyQuestionOption_CreateAsync(int answeredsurveyid, int surveyquestionoptionid, bool isselected);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatabaseVersion_Get", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.DatabaseVersion_GetResponse> DatabaseVersion_GetAsync(osVodigiPlayer.osVodigiWS.DatabaseVersion_GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Player_GetByName", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.Player_GetByNameResponse> Player_GetByNameAsync(osVodigiPlayer.osVodigiWS.Player_GetByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Player_GetCurrentSchedule", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.Player_GetCurrentScheduleResponse> Player_GetCurrentScheduleAsync(osVodigiPlayer.osVodigiWS.Player_GetCurrentScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Player_GetMediaToDownload", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.Player_GetMediaToDownloadResponse> Player_GetMediaToDownloadAsync(osVodigiPlayer.osVodigiWS.Player_GetMediaToDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerScreenContentLog_Create", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.PlayerScreenContentLog_CreateResponse> PlayerScreenContentLog_CreateAsync(osVodigiPlayer.osVodigiWS.PlayerScreenContentLog_CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerScreenContentLog_UpdateCloseDateTime", ReplyAction="*")]
        System.Threading.Tasks.Task PlayerScreenContentLog_UpdateCloseDateTimeAsync(int playerscreencontentlogid, System.DateTime closedatetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerScreenLog_Create", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.PlayerScreenLog_CreateResponse> PlayerScreenLog_CreateAsync(osVodigiPlayer.osVodigiWS.PlayerScreenLog_CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerScreenLog_UpdateCloseDateTime", ReplyAction="*")]
        System.Threading.Tasks.Task PlayerScreenLog_UpdateCloseDateTimeAsync(int playerscreenlogid, System.DateTime closedatetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/User_Validate", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.User_ValidateResponse> User_ValidateAsync(osVodigiPlayer.osVodigiWS.User_ValidateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Account_GetByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Account_GetByName", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.Account_GetByNameRequestBody Body;
        
        public Account_GetByNameRequest()
        {
        }
        
        public Account_GetByNameRequest(osVodigiPlayer.osVodigiWS.Account_GetByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Account_GetByNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountname;
        
        public Account_GetByNameRequestBody()
        {
        }
        
        public Account_GetByNameRequestBody(string accountname)
        {
            this.accountname = accountname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Account_GetByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Account_GetByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.Account_GetByNameResponseBody Body;
        
        public Account_GetByNameResponse()
        {
        }
        
        public Account_GetByNameResponse(osVodigiPlayer.osVodigiWS.Account_GetByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Account_GetByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public osVodigiPlayer.osVodigiWS.Account Account_GetByNameResult;
        
        public Account_GetByNameResponseBody()
        {
        }
        
        public Account_GetByNameResponseBody(osVodigiPlayer.osVodigiWS.Account Account_GetByNameResult)
        {
            this.Account_GetByNameResult = Account_GetByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivityLog_CreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivityLog_Create", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.ActivityLog_CreateRequestBody Body;
        
        public ActivityLog_CreateRequest()
        {
        }
        
        public ActivityLog_CreateRequest(osVodigiPlayer.osVodigiWS.ActivityLog_CreateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivityLog_CreateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string entitytype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string entityaction;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime activitydatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string activitydetails;
        
        public ActivityLog_CreateRequestBody()
        {
        }
        
        public ActivityLog_CreateRequestBody(int accountid, int userid, string entitytype, string entityaction, System.DateTime activitydatetime, string activitydetails)
        {
            this.accountid = accountid;
            this.userid = userid;
            this.entitytype = entitytype;
            this.entityaction = entityaction;
            this.activitydatetime = activitydatetime;
            this.activitydetails = activitydetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivityLog_CreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivityLog_CreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.ActivityLog_CreateResponseBody Body;
        
        public ActivityLog_CreateResponse()
        {
        }
        
        public ActivityLog_CreateResponse(osVodigiPlayer.osVodigiWS.ActivityLog_CreateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ActivityLog_CreateResponseBody
    {
        
        public ActivityLog_CreateResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatabaseVersion_GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatabaseVersion_Get", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.DatabaseVersion_GetRequestBody Body;
        
        public DatabaseVersion_GetRequest()
        {
        }
        
        public DatabaseVersion_GetRequest(osVodigiPlayer.osVodigiWS.DatabaseVersion_GetRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DatabaseVersion_GetRequestBody
    {
        
        public DatabaseVersion_GetRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatabaseVersion_GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatabaseVersion_GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.DatabaseVersion_GetResponseBody Body;
        
        public DatabaseVersion_GetResponse()
        {
        }
        
        public DatabaseVersion_GetResponse(osVodigiPlayer.osVodigiWS.DatabaseVersion_GetResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatabaseVersion_GetResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public osVodigiPlayer.osVodigiWS.DatabaseVersion DatabaseVersion_GetResult;
        
        public DatabaseVersion_GetResponseBody()
        {
        }
        
        public DatabaseVersion_GetResponseBody(osVodigiPlayer.osVodigiWS.DatabaseVersion DatabaseVersion_GetResult)
        {
            this.DatabaseVersion_GetResult = DatabaseVersion_GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Player_GetByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player_GetByName", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.Player_GetByNameRequestBody Body;
        
        public Player_GetByNameRequest()
        {
        }
        
        public Player_GetByNameRequest(osVodigiPlayer.osVodigiWS.Player_GetByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Player_GetByNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string playername;
        
        public Player_GetByNameRequestBody()
        {
        }
        
        public Player_GetByNameRequestBody(int accountid, string playername)
        {
            this.accountid = accountid;
            this.playername = playername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Player_GetByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player_GetByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.Player_GetByNameResponseBody Body;
        
        public Player_GetByNameResponse()
        {
        }
        
        public Player_GetByNameResponse(osVodigiPlayer.osVodigiWS.Player_GetByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Player_GetByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public osVodigiPlayer.osVodigiWS.Player Player_GetByNameResult;
        
        public Player_GetByNameResponseBody()
        {
        }
        
        public Player_GetByNameResponseBody(osVodigiPlayer.osVodigiWS.Player Player_GetByNameResult)
        {
            this.Player_GetByNameResult = Player_GetByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Player_GetCurrentScheduleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player_GetCurrentSchedule", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.Player_GetCurrentScheduleRequestBody Body;
        
        public Player_GetCurrentScheduleRequest()
        {
        }
        
        public Player_GetCurrentScheduleRequest(osVodigiPlayer.osVodigiWS.Player_GetCurrentScheduleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Player_GetCurrentScheduleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int playerid;
        
        public Player_GetCurrentScheduleRequestBody()
        {
        }
        
        public Player_GetCurrentScheduleRequestBody(int playerid)
        {
            this.playerid = playerid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Player_GetCurrentScheduleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player_GetCurrentScheduleResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.Player_GetCurrentScheduleResponseBody Body;
        
        public Player_GetCurrentScheduleResponse()
        {
        }
        
        public Player_GetCurrentScheduleResponse(osVodigiPlayer.osVodigiWS.Player_GetCurrentScheduleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Player_GetCurrentScheduleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Player_GetCurrentScheduleResult;
        
        public Player_GetCurrentScheduleResponseBody()
        {
        }
        
        public Player_GetCurrentScheduleResponseBody(string Player_GetCurrentScheduleResult)
        {
            this.Player_GetCurrentScheduleResult = Player_GetCurrentScheduleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Player_GetMediaToDownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player_GetMediaToDownload", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.Player_GetMediaToDownloadRequestBody Body;
        
        public Player_GetMediaToDownloadRequest()
        {
        }
        
        public Player_GetMediaToDownloadRequest(osVodigiPlayer.osVodigiWS.Player_GetMediaToDownloadRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Player_GetMediaToDownloadRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountid;
        
        public Player_GetMediaToDownloadRequestBody()
        {
        }
        
        public Player_GetMediaToDownloadRequestBody(int accountid)
        {
            this.accountid = accountid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Player_GetMediaToDownloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player_GetMediaToDownloadResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.Player_GetMediaToDownloadResponseBody Body;
        
        public Player_GetMediaToDownloadResponse()
        {
        }
        
        public Player_GetMediaToDownloadResponse(osVodigiPlayer.osVodigiWS.Player_GetMediaToDownloadResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Player_GetMediaToDownloadResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Player_GetMediaToDownloadResult;
        
        public Player_GetMediaToDownloadResponseBody()
        {
        }
        
        public Player_GetMediaToDownloadResponseBody(string Player_GetMediaToDownloadResult)
        {
            this.Player_GetMediaToDownloadResult = Player_GetMediaToDownloadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayerScreenContentLog_CreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayerScreenContentLog_Create", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.PlayerScreenContentLog_CreateRequestBody Body;
        
        public PlayerScreenContentLog_CreateRequest()
        {
        }
        
        public PlayerScreenContentLog_CreateRequest(osVodigiPlayer.osVodigiWS.PlayerScreenContentLog_CreateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayerScreenContentLog_CreateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int playerid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string playername;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int screenid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string screenname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int screencontentid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string screencontentname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int screencontenttypeid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string screencontenttypename;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime displaydatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.DateTime closedatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string contentdetails;
        
        public PlayerScreenContentLog_CreateRequestBody()
        {
        }
        
        public PlayerScreenContentLog_CreateRequestBody(int accountid, int playerid, string playername, int screenid, string screenname, int screencontentid, string screencontentname, int screencontenttypeid, string screencontenttypename, System.DateTime displaydatetime, System.DateTime closedatetime, string contentdetails)
        {
            this.accountid = accountid;
            this.playerid = playerid;
            this.playername = playername;
            this.screenid = screenid;
            this.screenname = screenname;
            this.screencontentid = screencontentid;
            this.screencontentname = screencontentname;
            this.screencontenttypeid = screencontenttypeid;
            this.screencontenttypename = screencontenttypename;
            this.displaydatetime = displaydatetime;
            this.closedatetime = closedatetime;
            this.contentdetails = contentdetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayerScreenContentLog_CreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayerScreenContentLog_CreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.PlayerScreenContentLog_CreateResponseBody Body;
        
        public PlayerScreenContentLog_CreateResponse()
        {
        }
        
        public PlayerScreenContentLog_CreateResponse(osVodigiPlayer.osVodigiWS.PlayerScreenContentLog_CreateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayerScreenContentLog_CreateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PlayerScreenContentLog_CreateResult;
        
        public PlayerScreenContentLog_CreateResponseBody()
        {
        }
        
        public PlayerScreenContentLog_CreateResponseBody(int PlayerScreenContentLog_CreateResult)
        {
            this.PlayerScreenContentLog_CreateResult = PlayerScreenContentLog_CreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayerScreenLog_CreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayerScreenLog_Create", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.PlayerScreenLog_CreateRequestBody Body;
        
        public PlayerScreenLog_CreateRequest()
        {
        }
        
        public PlayerScreenLog_CreateRequest(osVodigiPlayer.osVodigiWS.PlayerScreenLog_CreateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayerScreenLog_CreateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int playerid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string playername;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int screenid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string screenname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime displaydatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime closedatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string screendetails;
        
        public PlayerScreenLog_CreateRequestBody()
        {
        }
        
        public PlayerScreenLog_CreateRequestBody(int accountid, int playerid, string playername, int screenid, string screenname, System.DateTime displaydatetime, System.DateTime closedatetime, string screendetails)
        {
            this.accountid = accountid;
            this.playerid = playerid;
            this.playername = playername;
            this.screenid = screenid;
            this.screenname = screenname;
            this.displaydatetime = displaydatetime;
            this.closedatetime = closedatetime;
            this.screendetails = screendetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayerScreenLog_CreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayerScreenLog_CreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.PlayerScreenLog_CreateResponseBody Body;
        
        public PlayerScreenLog_CreateResponse()
        {
        }
        
        public PlayerScreenLog_CreateResponse(osVodigiPlayer.osVodigiWS.PlayerScreenLog_CreateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayerScreenLog_CreateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PlayerScreenLog_CreateResult;
        
        public PlayerScreenLog_CreateResponseBody()
        {
        }
        
        public PlayerScreenLog_CreateResponseBody(int PlayerScreenLog_CreateResult)
        {
            this.PlayerScreenLog_CreateResult = PlayerScreenLog_CreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class User_ValidateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="User_Validate", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.User_ValidateRequestBody Body;
        
        public User_ValidateRequest()
        {
        }
        
        public User_ValidateRequest(osVodigiPlayer.osVodigiWS.User_ValidateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class User_ValidateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public User_ValidateRequestBody()
        {
        }
        
        public User_ValidateRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class User_ValidateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="User_ValidateResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiPlayer.osVodigiWS.User_ValidateResponseBody Body;
        
        public User_ValidateResponse()
        {
        }
        
        public User_ValidateResponse(osVodigiPlayer.osVodigiWS.User_ValidateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class User_ValidateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public osVodigiPlayer.osVodigiWS.UserAccount User_ValidateResult;
        
        public User_ValidateResponseBody()
        {
        }
        
        public User_ValidateResponseBody(osVodigiPlayer.osVodigiWS.UserAccount User_ValidateResult)
        {
            this.User_ValidateResult = User_ValidateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface osVodigiServiceSoapChannel : osVodigiPlayer.osVodigiWS.osVodigiServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class osVodigiServiceSoapClient : System.ServiceModel.ClientBase<osVodigiPlayer.osVodigiWS.osVodigiServiceSoap>, osVodigiPlayer.osVodigiWS.osVodigiServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public osVodigiServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(osVodigiServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), osVodigiServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public osVodigiServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(osVodigiServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public osVodigiServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(osVodigiServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public osVodigiServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.Account_GetByNameResponse> osVodigiPlayer.osVodigiWS.osVodigiServiceSoap.Account_GetByNameAsync(osVodigiPlayer.osVodigiWS.Account_GetByNameRequest request)
        {
            return base.Channel.Account_GetByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.Account_GetByNameResponse> Account_GetByNameAsync(string accountname)
        {
            osVodigiPlayer.osVodigiWS.Account_GetByNameRequest inValue = new osVodigiPlayer.osVodigiWS.Account_GetByNameRequest();
            inValue.Body = new osVodigiPlayer.osVodigiWS.Account_GetByNameRequestBody();
            inValue.Body.accountname = accountname;
            return ((osVodigiPlayer.osVodigiWS.osVodigiServiceSoap)(this)).Account_GetByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.ActivityLog_CreateResponse> osVodigiPlayer.osVodigiWS.osVodigiServiceSoap.ActivityLog_CreateAsync(osVodigiPlayer.osVodigiWS.ActivityLog_CreateRequest request)
        {
            return base.Channel.ActivityLog_CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.ActivityLog_CreateResponse> ActivityLog_CreateAsync(int accountid, int userid, string entitytype, string entityaction, System.DateTime activitydatetime, string activitydetails)
        {
            osVodigiPlayer.osVodigiWS.ActivityLog_CreateRequest inValue = new osVodigiPlayer.osVodigiWS.ActivityLog_CreateRequest();
            inValue.Body = new osVodigiPlayer.osVodigiWS.ActivityLog_CreateRequestBody();
            inValue.Body.accountid = accountid;
            inValue.Body.userid = userid;
            inValue.Body.entitytype = entitytype;
            inValue.Body.entityaction = entityaction;
            inValue.Body.activitydatetime = activitydatetime;
            inValue.Body.activitydetails = activitydetails;
            return ((osVodigiPlayer.osVodigiWS.osVodigiServiceSoap)(this)).ActivityLog_CreateAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> AnsweredSurvey_CreateAsync(int accountid, int surveyid, int playerid)
        {
            return base.Channel.AnsweredSurvey_CreateAsync(accountid, surveyid, playerid);
        }
        
        public System.Threading.Tasks.Task<int> AnsweredSurveyQuestionOption_CreateAsync(int answeredsurveyid, int surveyquestionoptionid, bool isselected)
        {
            return base.Channel.AnsweredSurveyQuestionOption_CreateAsync(answeredsurveyid, surveyquestionoptionid, isselected);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.DatabaseVersion_GetResponse> osVodigiPlayer.osVodigiWS.osVodigiServiceSoap.DatabaseVersion_GetAsync(osVodigiPlayer.osVodigiWS.DatabaseVersion_GetRequest request)
        {
            return base.Channel.DatabaseVersion_GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.DatabaseVersion_GetResponse> DatabaseVersion_GetAsync()
        {
            osVodigiPlayer.osVodigiWS.DatabaseVersion_GetRequest inValue = new osVodigiPlayer.osVodigiWS.DatabaseVersion_GetRequest();
            inValue.Body = new osVodigiPlayer.osVodigiWS.DatabaseVersion_GetRequestBody();
            return ((osVodigiPlayer.osVodigiWS.osVodigiServiceSoap)(this)).DatabaseVersion_GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.Player_GetByNameResponse> osVodigiPlayer.osVodigiWS.osVodigiServiceSoap.Player_GetByNameAsync(osVodigiPlayer.osVodigiWS.Player_GetByNameRequest request)
        {
            return base.Channel.Player_GetByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.Player_GetByNameResponse> Player_GetByNameAsync(int accountid, string playername)
        {
            osVodigiPlayer.osVodigiWS.Player_GetByNameRequest inValue = new osVodigiPlayer.osVodigiWS.Player_GetByNameRequest();
            inValue.Body = new osVodigiPlayer.osVodigiWS.Player_GetByNameRequestBody();
            inValue.Body.accountid = accountid;
            inValue.Body.playername = playername;
            return ((osVodigiPlayer.osVodigiWS.osVodigiServiceSoap)(this)).Player_GetByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.Player_GetCurrentScheduleResponse> osVodigiPlayer.osVodigiWS.osVodigiServiceSoap.Player_GetCurrentScheduleAsync(osVodigiPlayer.osVodigiWS.Player_GetCurrentScheduleRequest request)
        {
            return base.Channel.Player_GetCurrentScheduleAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.Player_GetCurrentScheduleResponse> Player_GetCurrentScheduleAsync(int playerid)
        {
            osVodigiPlayer.osVodigiWS.Player_GetCurrentScheduleRequest inValue = new osVodigiPlayer.osVodigiWS.Player_GetCurrentScheduleRequest();
            inValue.Body = new osVodigiPlayer.osVodigiWS.Player_GetCurrentScheduleRequestBody();
            inValue.Body.playerid = playerid;
            return ((osVodigiPlayer.osVodigiWS.osVodigiServiceSoap)(this)).Player_GetCurrentScheduleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.Player_GetMediaToDownloadResponse> osVodigiPlayer.osVodigiWS.osVodigiServiceSoap.Player_GetMediaToDownloadAsync(osVodigiPlayer.osVodigiWS.Player_GetMediaToDownloadRequest request)
        {
            return base.Channel.Player_GetMediaToDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.Player_GetMediaToDownloadResponse> Player_GetMediaToDownloadAsync(int accountid)
        {
            osVodigiPlayer.osVodigiWS.Player_GetMediaToDownloadRequest inValue = new osVodigiPlayer.osVodigiWS.Player_GetMediaToDownloadRequest();
            inValue.Body = new osVodigiPlayer.osVodigiWS.Player_GetMediaToDownloadRequestBody();
            inValue.Body.accountid = accountid;
            return ((osVodigiPlayer.osVodigiWS.osVodigiServiceSoap)(this)).Player_GetMediaToDownloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.PlayerScreenContentLog_CreateResponse> osVodigiPlayer.osVodigiWS.osVodigiServiceSoap.PlayerScreenContentLog_CreateAsync(osVodigiPlayer.osVodigiWS.PlayerScreenContentLog_CreateRequest request)
        {
            return base.Channel.PlayerScreenContentLog_CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.PlayerScreenContentLog_CreateResponse> PlayerScreenContentLog_CreateAsync(int accountid, int playerid, string playername, int screenid, string screenname, int screencontentid, string screencontentname, int screencontenttypeid, string screencontenttypename, System.DateTime displaydatetime, System.DateTime closedatetime, string contentdetails)
        {
            osVodigiPlayer.osVodigiWS.PlayerScreenContentLog_CreateRequest inValue = new osVodigiPlayer.osVodigiWS.PlayerScreenContentLog_CreateRequest();
            inValue.Body = new osVodigiPlayer.osVodigiWS.PlayerScreenContentLog_CreateRequestBody();
            inValue.Body.accountid = accountid;
            inValue.Body.playerid = playerid;
            inValue.Body.playername = playername;
            inValue.Body.screenid = screenid;
            inValue.Body.screenname = screenname;
            inValue.Body.screencontentid = screencontentid;
            inValue.Body.screencontentname = screencontentname;
            inValue.Body.screencontenttypeid = screencontenttypeid;
            inValue.Body.screencontenttypename = screencontenttypename;
            inValue.Body.displaydatetime = displaydatetime;
            inValue.Body.closedatetime = closedatetime;
            inValue.Body.contentdetails = contentdetails;
            return ((osVodigiPlayer.osVodigiWS.osVodigiServiceSoap)(this)).PlayerScreenContentLog_CreateAsync(inValue);
        }
        
        public System.Threading.Tasks.Task PlayerScreenContentLog_UpdateCloseDateTimeAsync(int playerscreencontentlogid, System.DateTime closedatetime)
        {
            return base.Channel.PlayerScreenContentLog_UpdateCloseDateTimeAsync(playerscreencontentlogid, closedatetime);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.PlayerScreenLog_CreateResponse> osVodigiPlayer.osVodigiWS.osVodigiServiceSoap.PlayerScreenLog_CreateAsync(osVodigiPlayer.osVodigiWS.PlayerScreenLog_CreateRequest request)
        {
            return base.Channel.PlayerScreenLog_CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.PlayerScreenLog_CreateResponse> PlayerScreenLog_CreateAsync(int accountid, int playerid, string playername, int screenid, string screenname, System.DateTime displaydatetime, System.DateTime closedatetime, string screendetails)
        {
            osVodigiPlayer.osVodigiWS.PlayerScreenLog_CreateRequest inValue = new osVodigiPlayer.osVodigiWS.PlayerScreenLog_CreateRequest();
            inValue.Body = new osVodigiPlayer.osVodigiWS.PlayerScreenLog_CreateRequestBody();
            inValue.Body.accountid = accountid;
            inValue.Body.playerid = playerid;
            inValue.Body.playername = playername;
            inValue.Body.screenid = screenid;
            inValue.Body.screenname = screenname;
            inValue.Body.displaydatetime = displaydatetime;
            inValue.Body.closedatetime = closedatetime;
            inValue.Body.screendetails = screendetails;
            return ((osVodigiPlayer.osVodigiWS.osVodigiServiceSoap)(this)).PlayerScreenLog_CreateAsync(inValue);
        }
        
        public System.Threading.Tasks.Task PlayerScreenLog_UpdateCloseDateTimeAsync(int playerscreenlogid, System.DateTime closedatetime)
        {
            return base.Channel.PlayerScreenLog_UpdateCloseDateTimeAsync(playerscreenlogid, closedatetime);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.User_ValidateResponse> osVodigiPlayer.osVodigiWS.osVodigiServiceSoap.User_ValidateAsync(osVodigiPlayer.osVodigiWS.User_ValidateRequest request)
        {
            return base.Channel.User_ValidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiPlayer.osVodigiWS.User_ValidateResponse> User_ValidateAsync(string username, string password)
        {
            osVodigiPlayer.osVodigiWS.User_ValidateRequest inValue = new osVodigiPlayer.osVodigiWS.User_ValidateRequest();
            inValue.Body = new osVodigiPlayer.osVodigiWS.User_ValidateRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((osVodigiPlayer.osVodigiWS.osVodigiServiceSoap)(this)).User_ValidateAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.osVodigiServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.osVodigiServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.osVodigiServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:52713/osVodigiService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.osVodigiServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:52713/osVodigiService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            osVodigiServiceSoap,
            
            osVodigiServiceSoap12,
        }
    }
}
