//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace osVodigiWeb6xTests.osVodigiWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FTPServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FTPUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FTPPasswordField;
        
        private bool IsActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountDescription {
            get {
                return this.AccountDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountDescriptionField, value) != true)) {
                    this.AccountDescriptionField = value;
                    this.RaisePropertyChanged("AccountDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FTPServer {
            get {
                return this.FTPServerField;
            }
            set {
                if ((object.ReferenceEquals(this.FTPServerField, value) != true)) {
                    this.FTPServerField = value;
                    this.RaisePropertyChanged("FTPServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FTPUsername {
            get {
                return this.FTPUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.FTPUsernameField, value) != true)) {
                    this.FTPUsernameField = value;
                    this.RaisePropertyChanged("FTPUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FTPPassword {
            get {
                return this.FTPPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.FTPPasswordField, value) != true)) {
                    this.FTPPasswordField = value;
                    this.RaisePropertyChanged("FTPPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseVersion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DatabaseVersion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DatabaseVersionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        private System.DateTime DateInstalledField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DatabaseVersionID {
            get {
                return this.DatabaseVersionIDField;
            }
            set {
                if ((this.DatabaseVersionIDField.Equals(value) != true)) {
                    this.DatabaseVersionIDField = value;
                    this.RaisePropertyChanged("DatabaseVersionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime DateInstalled {
            get {
                return this.DateInstalledField;
            }
            set {
                if ((this.DateInstalledField.Equals(value) != true)) {
                    this.DateInstalledField = value;
                    this.RaisePropertyChanged("DateInstalled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PlayerIDField;
        
        private int AccountIDField;
        
        private int PlayerGroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerDescriptionField;
        
        private bool IsActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PlayerID {
            get {
                return this.PlayerIDField;
            }
            set {
                if ((this.PlayerIDField.Equals(value) != true)) {
                    this.PlayerIDField = value;
                    this.RaisePropertyChanged("PlayerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PlayerGroupID {
            get {
                return this.PlayerGroupIDField;
            }
            set {
                if ((this.PlayerGroupIDField.Equals(value) != true)) {
                    this.PlayerGroupIDField = value;
                    this.RaisePropertyChanged("PlayerGroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PlayerLocation {
            get {
                return this.PlayerLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerLocationField, value) != true)) {
                    this.PlayerLocationField = value;
                    this.RaisePropertyChanged("PlayerLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PlayerDescription {
            get {
                return this.PlayerDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerDescriptionField, value) != true)) {
                    this.PlayerDescriptionField = value;
                    this.RaisePropertyChanged("PlayerDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UserIDField;
        
        private int AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        private bool IsAdminField;
        
        private bool UserIsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FTPServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FTPUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FTPPasswordField;
        
        private bool AccountIsActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool UserIsActive {
            get {
                return this.UserIsActiveField;
            }
            set {
                if ((this.UserIsActiveField.Equals(value) != true)) {
                    this.UserIsActiveField = value;
                    this.RaisePropertyChanged("UserIsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string AccountDescription {
            get {
                return this.AccountDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountDescriptionField, value) != true)) {
                    this.AccountDescriptionField = value;
                    this.RaisePropertyChanged("AccountDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string FTPServer {
            get {
                return this.FTPServerField;
            }
            set {
                if ((object.ReferenceEquals(this.FTPServerField, value) != true)) {
                    this.FTPServerField = value;
                    this.RaisePropertyChanged("FTPServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string FTPUsername {
            get {
                return this.FTPUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.FTPUsernameField, value) != true)) {
                    this.FTPUsernameField = value;
                    this.RaisePropertyChanged("FTPUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string FTPPassword {
            get {
                return this.FTPPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.FTPPasswordField, value) != true)) {
                    this.FTPPasswordField = value;
                    this.RaisePropertyChanged("FTPPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool AccountIsActive {
            get {
                return this.AccountIsActiveField;
            }
            set {
                if ((this.AccountIsActiveField.Equals(value) != true)) {
                    this.AccountIsActiveField = value;
                    this.RaisePropertyChanged("AccountIsActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="osVodigiWS.osVodigiServiceSoap")]
    public interface osVodigiServiceSoap {
        
        // CODEGEN: Generating message contract since element name accountname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account_GetByName", ReplyAction="*")]
        osVodigiWeb6xTests.osVodigiWS.Account_GetByNameResponse Account_GetByName(osVodigiWeb6xTests.osVodigiWS.Account_GetByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account_GetByName", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.Account_GetByNameResponse> Account_GetByNameAsync(osVodigiWeb6xTests.osVodigiWS.Account_GetByNameRequest request);
        
        // CODEGEN: Generating message contract since element name entitytype from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActivityLog_Create", ReplyAction="*")]
        osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateResponse ActivityLog_Create(osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActivityLog_Create", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateResponse> ActivityLog_CreateAsync(osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnsweredSurvey_Create", ReplyAction="*")]
        int AnsweredSurvey_Create(int accountid, int surveyid, int playerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnsweredSurvey_Create", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AnsweredSurvey_CreateAsync(int accountid, int surveyid, int playerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnsweredSurveyQuestionOption_Create", ReplyAction="*")]
        int AnsweredSurveyQuestionOption_Create(int answeredsurveyid, int surveyquestionoptionid, bool isselected);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnsweredSurveyQuestionOption_Create", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AnsweredSurveyQuestionOption_CreateAsync(int answeredsurveyid, int surveyquestionoptionid, bool isselected);
        
        // CODEGEN: Generating message contract since element name DatabaseVersion_GetResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatabaseVersion_Get", ReplyAction="*")]
        osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetResponse DatabaseVersion_Get(osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatabaseVersion_Get", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetResponse> DatabaseVersion_GetAsync(osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetRequest request);
        
        // CODEGEN: Generating message contract since element name playername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Player_GetByName", ReplyAction="*")]
        osVodigiWeb6xTests.osVodigiWS.Player_GetByNameResponse Player_GetByName(osVodigiWeb6xTests.osVodigiWS.Player_GetByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Player_GetByName", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.Player_GetByNameResponse> Player_GetByNameAsync(osVodigiWeb6xTests.osVodigiWS.Player_GetByNameRequest request);
        
        // CODEGEN: Generating message contract since element name Player_GetCurrentScheduleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Player_GetCurrentSchedule", ReplyAction="*")]
        osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleResponse Player_GetCurrentSchedule(osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Player_GetCurrentSchedule", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleResponse> Player_GetCurrentScheduleAsync(osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleRequest request);
        
        // CODEGEN: Generating message contract since element name Player_GetMediaToDownloadResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Player_GetMediaToDownload", ReplyAction="*")]
        osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadResponse Player_GetMediaToDownload(osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Player_GetMediaToDownload", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadResponse> Player_GetMediaToDownloadAsync(osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadRequest request);
        
        // CODEGEN: Generating message contract since element name playername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerScreenContentLog_Create", ReplyAction="*")]
        osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateResponse PlayerScreenContentLog_Create(osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerScreenContentLog_Create", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateResponse> PlayerScreenContentLog_CreateAsync(osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerScreenContentLog_UpdateCloseDateTime", ReplyAction="*")]
        void PlayerScreenContentLog_UpdateCloseDateTime(int playerscreencontentlogid, System.DateTime closedatetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerScreenContentLog_UpdateCloseDateTime", ReplyAction="*")]
        System.Threading.Tasks.Task PlayerScreenContentLog_UpdateCloseDateTimeAsync(int playerscreencontentlogid, System.DateTime closedatetime);
        
        // CODEGEN: Generating message contract since element name playername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerScreenLog_Create", ReplyAction="*")]
        osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateResponse PlayerScreenLog_Create(osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerScreenLog_Create", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateResponse> PlayerScreenLog_CreateAsync(osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerScreenLog_UpdateCloseDateTime", ReplyAction="*")]
        void PlayerScreenLog_UpdateCloseDateTime(int playerscreenlogid, System.DateTime closedatetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerScreenLog_UpdateCloseDateTime", ReplyAction="*")]
        System.Threading.Tasks.Task PlayerScreenLog_UpdateCloseDateTimeAsync(int playerscreenlogid, System.DateTime closedatetime);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/User_Validate", ReplyAction="*")]
        osVodigiWeb6xTests.osVodigiWS.User_ValidateResponse User_Validate(osVodigiWeb6xTests.osVodigiWS.User_ValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/User_Validate", ReplyAction="*")]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.User_ValidateResponse> User_ValidateAsync(osVodigiWeb6xTests.osVodigiWS.User_ValidateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Account_GetByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Account_GetByName", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.Account_GetByNameRequestBody Body;
        
        public Account_GetByNameRequest() {
        }
        
        public Account_GetByNameRequest(osVodigiWeb6xTests.osVodigiWS.Account_GetByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Account_GetByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountname;
        
        public Account_GetByNameRequestBody() {
        }
        
        public Account_GetByNameRequestBody(string accountname) {
            this.accountname = accountname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Account_GetByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Account_GetByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.Account_GetByNameResponseBody Body;
        
        public Account_GetByNameResponse() {
        }
        
        public Account_GetByNameResponse(osVodigiWeb6xTests.osVodigiWS.Account_GetByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Account_GetByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.Account Account_GetByNameResult;
        
        public Account_GetByNameResponseBody() {
        }
        
        public Account_GetByNameResponseBody(osVodigiWeb6xTests.osVodigiWS.Account Account_GetByNameResult) {
            this.Account_GetByNameResult = Account_GetByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivityLog_CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivityLog_Create", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateRequestBody Body;
        
        public ActivityLog_CreateRequest() {
        }
        
        public ActivityLog_CreateRequest(osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivityLog_CreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string entitytype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string entityaction;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime activitydatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string activitydetails;
        
        public ActivityLog_CreateRequestBody() {
        }
        
        public ActivityLog_CreateRequestBody(int accountid, int userid, string entitytype, string entityaction, System.DateTime activitydatetime, string activitydetails) {
            this.accountid = accountid;
            this.userid = userid;
            this.entitytype = entitytype;
            this.entityaction = entityaction;
            this.activitydatetime = activitydatetime;
            this.activitydetails = activitydetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivityLog_CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivityLog_CreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateResponseBody Body;
        
        public ActivityLog_CreateResponse() {
        }
        
        public ActivityLog_CreateResponse(osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ActivityLog_CreateResponseBody {
        
        public ActivityLog_CreateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatabaseVersion_GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatabaseVersion_Get", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetRequestBody Body;
        
        public DatabaseVersion_GetRequest() {
        }
        
        public DatabaseVersion_GetRequest(osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DatabaseVersion_GetRequestBody {
        
        public DatabaseVersion_GetRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatabaseVersion_GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatabaseVersion_GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetResponseBody Body;
        
        public DatabaseVersion_GetResponse() {
        }
        
        public DatabaseVersion_GetResponse(osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatabaseVersion_GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.DatabaseVersion DatabaseVersion_GetResult;
        
        public DatabaseVersion_GetResponseBody() {
        }
        
        public DatabaseVersion_GetResponseBody(osVodigiWeb6xTests.osVodigiWS.DatabaseVersion DatabaseVersion_GetResult) {
            this.DatabaseVersion_GetResult = DatabaseVersion_GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Player_GetByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player_GetByName", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.Player_GetByNameRequestBody Body;
        
        public Player_GetByNameRequest() {
        }
        
        public Player_GetByNameRequest(osVodigiWeb6xTests.osVodigiWS.Player_GetByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Player_GetByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string playername;
        
        public Player_GetByNameRequestBody() {
        }
        
        public Player_GetByNameRequestBody(int accountid, string playername) {
            this.accountid = accountid;
            this.playername = playername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Player_GetByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player_GetByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.Player_GetByNameResponseBody Body;
        
        public Player_GetByNameResponse() {
        }
        
        public Player_GetByNameResponse(osVodigiWeb6xTests.osVodigiWS.Player_GetByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Player_GetByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.Player Player_GetByNameResult;
        
        public Player_GetByNameResponseBody() {
        }
        
        public Player_GetByNameResponseBody(osVodigiWeb6xTests.osVodigiWS.Player Player_GetByNameResult) {
            this.Player_GetByNameResult = Player_GetByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Player_GetCurrentScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player_GetCurrentSchedule", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleRequestBody Body;
        
        public Player_GetCurrentScheduleRequest() {
        }
        
        public Player_GetCurrentScheduleRequest(osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Player_GetCurrentScheduleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int playerid;
        
        public Player_GetCurrentScheduleRequestBody() {
        }
        
        public Player_GetCurrentScheduleRequestBody(int playerid) {
            this.playerid = playerid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Player_GetCurrentScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player_GetCurrentScheduleResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleResponseBody Body;
        
        public Player_GetCurrentScheduleResponse() {
        }
        
        public Player_GetCurrentScheduleResponse(osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Player_GetCurrentScheduleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Player_GetCurrentScheduleResult;
        
        public Player_GetCurrentScheduleResponseBody() {
        }
        
        public Player_GetCurrentScheduleResponseBody(string Player_GetCurrentScheduleResult) {
            this.Player_GetCurrentScheduleResult = Player_GetCurrentScheduleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Player_GetMediaToDownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player_GetMediaToDownload", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadRequestBody Body;
        
        public Player_GetMediaToDownloadRequest() {
        }
        
        public Player_GetMediaToDownloadRequest(osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Player_GetMediaToDownloadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountid;
        
        public Player_GetMediaToDownloadRequestBody() {
        }
        
        public Player_GetMediaToDownloadRequestBody(int accountid) {
            this.accountid = accountid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Player_GetMediaToDownloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player_GetMediaToDownloadResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadResponseBody Body;
        
        public Player_GetMediaToDownloadResponse() {
        }
        
        public Player_GetMediaToDownloadResponse(osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Player_GetMediaToDownloadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Player_GetMediaToDownloadResult;
        
        public Player_GetMediaToDownloadResponseBody() {
        }
        
        public Player_GetMediaToDownloadResponseBody(string Player_GetMediaToDownloadResult) {
            this.Player_GetMediaToDownloadResult = Player_GetMediaToDownloadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayerScreenContentLog_CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayerScreenContentLog_Create", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateRequestBody Body;
        
        public PlayerScreenContentLog_CreateRequest() {
        }
        
        public PlayerScreenContentLog_CreateRequest(osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayerScreenContentLog_CreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int playerid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string playername;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int screenid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string screenname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int screencontentid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string screencontentname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int screencontenttypeid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string screencontenttypename;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime displaydatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.DateTime closedatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string contentdetails;
        
        public PlayerScreenContentLog_CreateRequestBody() {
        }
        
        public PlayerScreenContentLog_CreateRequestBody(int accountid, int playerid, string playername, int screenid, string screenname, int screencontentid, string screencontentname, int screencontenttypeid, string screencontenttypename, System.DateTime displaydatetime, System.DateTime closedatetime, string contentdetails) {
            this.accountid = accountid;
            this.playerid = playerid;
            this.playername = playername;
            this.screenid = screenid;
            this.screenname = screenname;
            this.screencontentid = screencontentid;
            this.screencontentname = screencontentname;
            this.screencontenttypeid = screencontenttypeid;
            this.screencontenttypename = screencontenttypename;
            this.displaydatetime = displaydatetime;
            this.closedatetime = closedatetime;
            this.contentdetails = contentdetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayerScreenContentLog_CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayerScreenContentLog_CreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateResponseBody Body;
        
        public PlayerScreenContentLog_CreateResponse() {
        }
        
        public PlayerScreenContentLog_CreateResponse(osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayerScreenContentLog_CreateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PlayerScreenContentLog_CreateResult;
        
        public PlayerScreenContentLog_CreateResponseBody() {
        }
        
        public PlayerScreenContentLog_CreateResponseBody(int PlayerScreenContentLog_CreateResult) {
            this.PlayerScreenContentLog_CreateResult = PlayerScreenContentLog_CreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayerScreenLog_CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayerScreenLog_Create", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateRequestBody Body;
        
        public PlayerScreenLog_CreateRequest() {
        }
        
        public PlayerScreenLog_CreateRequest(osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayerScreenLog_CreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int playerid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string playername;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int screenid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string screenname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime displaydatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime closedatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string screendetails;
        
        public PlayerScreenLog_CreateRequestBody() {
        }
        
        public PlayerScreenLog_CreateRequestBody(int accountid, int playerid, string playername, int screenid, string screenname, System.DateTime displaydatetime, System.DateTime closedatetime, string screendetails) {
            this.accountid = accountid;
            this.playerid = playerid;
            this.playername = playername;
            this.screenid = screenid;
            this.screenname = screenname;
            this.displaydatetime = displaydatetime;
            this.closedatetime = closedatetime;
            this.screendetails = screendetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayerScreenLog_CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayerScreenLog_CreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateResponseBody Body;
        
        public PlayerScreenLog_CreateResponse() {
        }
        
        public PlayerScreenLog_CreateResponse(osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayerScreenLog_CreateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PlayerScreenLog_CreateResult;
        
        public PlayerScreenLog_CreateResponseBody() {
        }
        
        public PlayerScreenLog_CreateResponseBody(int PlayerScreenLog_CreateResult) {
            this.PlayerScreenLog_CreateResult = PlayerScreenLog_CreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class User_ValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="User_Validate", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.User_ValidateRequestBody Body;
        
        public User_ValidateRequest() {
        }
        
        public User_ValidateRequest(osVodigiWeb6xTests.osVodigiWS.User_ValidateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class User_ValidateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public User_ValidateRequestBody() {
        }
        
        public User_ValidateRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class User_ValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="User_ValidateResponse", Namespace="http://tempuri.org/", Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.User_ValidateResponseBody Body;
        
        public User_ValidateResponse() {
        }
        
        public User_ValidateResponse(osVodigiWeb6xTests.osVodigiWS.User_ValidateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class User_ValidateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public osVodigiWeb6xTests.osVodigiWS.UserAccount User_ValidateResult;
        
        public User_ValidateResponseBody() {
        }
        
        public User_ValidateResponseBody(osVodigiWeb6xTests.osVodigiWS.UserAccount User_ValidateResult) {
            this.User_ValidateResult = User_ValidateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface osVodigiServiceSoapChannel : osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class osVodigiServiceSoapClient : System.ServiceModel.ClientBase<osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap>, osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap {
        
        public osVodigiServiceSoapClient() {
        }
        
        public osVodigiServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public osVodigiServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public osVodigiServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public osVodigiServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        osVodigiWeb6xTests.osVodigiWS.Account_GetByNameResponse osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.Account_GetByName(osVodigiWeb6xTests.osVodigiWS.Account_GetByNameRequest request) {
            return base.Channel.Account_GetByName(request);
        }
        
        public osVodigiWeb6xTests.osVodigiWS.Account Account_GetByName(string accountname) {
            osVodigiWeb6xTests.osVodigiWS.Account_GetByNameRequest inValue = new osVodigiWeb6xTests.osVodigiWS.Account_GetByNameRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.Account_GetByNameRequestBody();
            inValue.Body.accountname = accountname;
            osVodigiWeb6xTests.osVodigiWS.Account_GetByNameResponse retVal = ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).Account_GetByName(inValue);
            return retVal.Body.Account_GetByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.Account_GetByNameResponse> osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.Account_GetByNameAsync(osVodigiWeb6xTests.osVodigiWS.Account_GetByNameRequest request) {
            return base.Channel.Account_GetByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.Account_GetByNameResponse> Account_GetByNameAsync(string accountname) {
            osVodigiWeb6xTests.osVodigiWS.Account_GetByNameRequest inValue = new osVodigiWeb6xTests.osVodigiWS.Account_GetByNameRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.Account_GetByNameRequestBody();
            inValue.Body.accountname = accountname;
            return ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).Account_GetByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateResponse osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.ActivityLog_Create(osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateRequest request) {
            return base.Channel.ActivityLog_Create(request);
        }
        
        public void ActivityLog_Create(int accountid, int userid, string entitytype, string entityaction, System.DateTime activitydatetime, string activitydetails) {
            osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateRequest inValue = new osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateRequestBody();
            inValue.Body.accountid = accountid;
            inValue.Body.userid = userid;
            inValue.Body.entitytype = entitytype;
            inValue.Body.entityaction = entityaction;
            inValue.Body.activitydatetime = activitydatetime;
            inValue.Body.activitydetails = activitydetails;
            osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateResponse retVal = ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).ActivityLog_Create(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateResponse> osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.ActivityLog_CreateAsync(osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateRequest request) {
            return base.Channel.ActivityLog_CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateResponse> ActivityLog_CreateAsync(int accountid, int userid, string entitytype, string entityaction, System.DateTime activitydatetime, string activitydetails) {
            osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateRequest inValue = new osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.ActivityLog_CreateRequestBody();
            inValue.Body.accountid = accountid;
            inValue.Body.userid = userid;
            inValue.Body.entitytype = entitytype;
            inValue.Body.entityaction = entityaction;
            inValue.Body.activitydatetime = activitydatetime;
            inValue.Body.activitydetails = activitydetails;
            return ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).ActivityLog_CreateAsync(inValue);
        }
        
        public int AnsweredSurvey_Create(int accountid, int surveyid, int playerid) {
            return base.Channel.AnsweredSurvey_Create(accountid, surveyid, playerid);
        }
        
        public System.Threading.Tasks.Task<int> AnsweredSurvey_CreateAsync(int accountid, int surveyid, int playerid) {
            return base.Channel.AnsweredSurvey_CreateAsync(accountid, surveyid, playerid);
        }
        
        public int AnsweredSurveyQuestionOption_Create(int answeredsurveyid, int surveyquestionoptionid, bool isselected) {
            return base.Channel.AnsweredSurveyQuestionOption_Create(answeredsurveyid, surveyquestionoptionid, isselected);
        }
        
        public System.Threading.Tasks.Task<int> AnsweredSurveyQuestionOption_CreateAsync(int answeredsurveyid, int surveyquestionoptionid, bool isselected) {
            return base.Channel.AnsweredSurveyQuestionOption_CreateAsync(answeredsurveyid, surveyquestionoptionid, isselected);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetResponse osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.DatabaseVersion_Get(osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetRequest request) {
            return base.Channel.DatabaseVersion_Get(request);
        }
        
        public osVodigiWeb6xTests.osVodigiWS.DatabaseVersion DatabaseVersion_Get() {
            osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetRequest inValue = new osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetRequestBody();
            osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetResponse retVal = ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).DatabaseVersion_Get(inValue);
            return retVal.Body.DatabaseVersion_GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetResponse> osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.DatabaseVersion_GetAsync(osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetRequest request) {
            return base.Channel.DatabaseVersion_GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetResponse> DatabaseVersion_GetAsync() {
            osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetRequest inValue = new osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.DatabaseVersion_GetRequestBody();
            return ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).DatabaseVersion_GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        osVodigiWeb6xTests.osVodigiWS.Player_GetByNameResponse osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.Player_GetByName(osVodigiWeb6xTests.osVodigiWS.Player_GetByNameRequest request) {
            return base.Channel.Player_GetByName(request);
        }
        
        public osVodigiWeb6xTests.osVodigiWS.Player Player_GetByName(int accountid, string playername) {
            osVodigiWeb6xTests.osVodigiWS.Player_GetByNameRequest inValue = new osVodigiWeb6xTests.osVodigiWS.Player_GetByNameRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.Player_GetByNameRequestBody();
            inValue.Body.accountid = accountid;
            inValue.Body.playername = playername;
            osVodigiWeb6xTests.osVodigiWS.Player_GetByNameResponse retVal = ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).Player_GetByName(inValue);
            return retVal.Body.Player_GetByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.Player_GetByNameResponse> osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.Player_GetByNameAsync(osVodigiWeb6xTests.osVodigiWS.Player_GetByNameRequest request) {
            return base.Channel.Player_GetByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.Player_GetByNameResponse> Player_GetByNameAsync(int accountid, string playername) {
            osVodigiWeb6xTests.osVodigiWS.Player_GetByNameRequest inValue = new osVodigiWeb6xTests.osVodigiWS.Player_GetByNameRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.Player_GetByNameRequestBody();
            inValue.Body.accountid = accountid;
            inValue.Body.playername = playername;
            return ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).Player_GetByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleResponse osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.Player_GetCurrentSchedule(osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleRequest request) {
            return base.Channel.Player_GetCurrentSchedule(request);
        }
        
        public string Player_GetCurrentSchedule(int playerid) {
            osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleRequest inValue = new osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleRequestBody();
            inValue.Body.playerid = playerid;
            osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleResponse retVal = ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).Player_GetCurrentSchedule(inValue);
            return retVal.Body.Player_GetCurrentScheduleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleResponse> osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.Player_GetCurrentScheduleAsync(osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleRequest request) {
            return base.Channel.Player_GetCurrentScheduleAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleResponse> Player_GetCurrentScheduleAsync(int playerid) {
            osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleRequest inValue = new osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.Player_GetCurrentScheduleRequestBody();
            inValue.Body.playerid = playerid;
            return ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).Player_GetCurrentScheduleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadResponse osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.Player_GetMediaToDownload(osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadRequest request) {
            return base.Channel.Player_GetMediaToDownload(request);
        }
        
        public string Player_GetMediaToDownload(int accountid) {
            osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadRequest inValue = new osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadRequestBody();
            inValue.Body.accountid = accountid;
            osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadResponse retVal = ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).Player_GetMediaToDownload(inValue);
            return retVal.Body.Player_GetMediaToDownloadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadResponse> osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.Player_GetMediaToDownloadAsync(osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadRequest request) {
            return base.Channel.Player_GetMediaToDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadResponse> Player_GetMediaToDownloadAsync(int accountid) {
            osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadRequest inValue = new osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.Player_GetMediaToDownloadRequestBody();
            inValue.Body.accountid = accountid;
            return ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).Player_GetMediaToDownloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateResponse osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.PlayerScreenContentLog_Create(osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateRequest request) {
            return base.Channel.PlayerScreenContentLog_Create(request);
        }
        
        public int PlayerScreenContentLog_Create(int accountid, int playerid, string playername, int screenid, string screenname, int screencontentid, string screencontentname, int screencontenttypeid, string screencontenttypename, System.DateTime displaydatetime, System.DateTime closedatetime, string contentdetails) {
            osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateRequest inValue = new osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateRequestBody();
            inValue.Body.accountid = accountid;
            inValue.Body.playerid = playerid;
            inValue.Body.playername = playername;
            inValue.Body.screenid = screenid;
            inValue.Body.screenname = screenname;
            inValue.Body.screencontentid = screencontentid;
            inValue.Body.screencontentname = screencontentname;
            inValue.Body.screencontenttypeid = screencontenttypeid;
            inValue.Body.screencontenttypename = screencontenttypename;
            inValue.Body.displaydatetime = displaydatetime;
            inValue.Body.closedatetime = closedatetime;
            inValue.Body.contentdetails = contentdetails;
            osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateResponse retVal = ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).PlayerScreenContentLog_Create(inValue);
            return retVal.Body.PlayerScreenContentLog_CreateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateResponse> osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.PlayerScreenContentLog_CreateAsync(osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateRequest request) {
            return base.Channel.PlayerScreenContentLog_CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateResponse> PlayerScreenContentLog_CreateAsync(int accountid, int playerid, string playername, int screenid, string screenname, int screencontentid, string screencontentname, int screencontenttypeid, string screencontenttypename, System.DateTime displaydatetime, System.DateTime closedatetime, string contentdetails) {
            osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateRequest inValue = new osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.PlayerScreenContentLog_CreateRequestBody();
            inValue.Body.accountid = accountid;
            inValue.Body.playerid = playerid;
            inValue.Body.playername = playername;
            inValue.Body.screenid = screenid;
            inValue.Body.screenname = screenname;
            inValue.Body.screencontentid = screencontentid;
            inValue.Body.screencontentname = screencontentname;
            inValue.Body.screencontenttypeid = screencontenttypeid;
            inValue.Body.screencontenttypename = screencontenttypename;
            inValue.Body.displaydatetime = displaydatetime;
            inValue.Body.closedatetime = closedatetime;
            inValue.Body.contentdetails = contentdetails;
            return ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).PlayerScreenContentLog_CreateAsync(inValue);
        }
        
        public void PlayerScreenContentLog_UpdateCloseDateTime(int playerscreencontentlogid, System.DateTime closedatetime) {
            base.Channel.PlayerScreenContentLog_UpdateCloseDateTime(playerscreencontentlogid, closedatetime);
        }
        
        public System.Threading.Tasks.Task PlayerScreenContentLog_UpdateCloseDateTimeAsync(int playerscreencontentlogid, System.DateTime closedatetime) {
            return base.Channel.PlayerScreenContentLog_UpdateCloseDateTimeAsync(playerscreencontentlogid, closedatetime);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateResponse osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.PlayerScreenLog_Create(osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateRequest request) {
            return base.Channel.PlayerScreenLog_Create(request);
        }
        
        public int PlayerScreenLog_Create(int accountid, int playerid, string playername, int screenid, string screenname, System.DateTime displaydatetime, System.DateTime closedatetime, string screendetails) {
            osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateRequest inValue = new osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateRequestBody();
            inValue.Body.accountid = accountid;
            inValue.Body.playerid = playerid;
            inValue.Body.playername = playername;
            inValue.Body.screenid = screenid;
            inValue.Body.screenname = screenname;
            inValue.Body.displaydatetime = displaydatetime;
            inValue.Body.closedatetime = closedatetime;
            inValue.Body.screendetails = screendetails;
            osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateResponse retVal = ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).PlayerScreenLog_Create(inValue);
            return retVal.Body.PlayerScreenLog_CreateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateResponse> osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.PlayerScreenLog_CreateAsync(osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateRequest request) {
            return base.Channel.PlayerScreenLog_CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateResponse> PlayerScreenLog_CreateAsync(int accountid, int playerid, string playername, int screenid, string screenname, System.DateTime displaydatetime, System.DateTime closedatetime, string screendetails) {
            osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateRequest inValue = new osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.PlayerScreenLog_CreateRequestBody();
            inValue.Body.accountid = accountid;
            inValue.Body.playerid = playerid;
            inValue.Body.playername = playername;
            inValue.Body.screenid = screenid;
            inValue.Body.screenname = screenname;
            inValue.Body.displaydatetime = displaydatetime;
            inValue.Body.closedatetime = closedatetime;
            inValue.Body.screendetails = screendetails;
            return ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).PlayerScreenLog_CreateAsync(inValue);
        }
        
        public void PlayerScreenLog_UpdateCloseDateTime(int playerscreenlogid, System.DateTime closedatetime) {
            base.Channel.PlayerScreenLog_UpdateCloseDateTime(playerscreenlogid, closedatetime);
        }
        
        public System.Threading.Tasks.Task PlayerScreenLog_UpdateCloseDateTimeAsync(int playerscreenlogid, System.DateTime closedatetime) {
            return base.Channel.PlayerScreenLog_UpdateCloseDateTimeAsync(playerscreenlogid, closedatetime);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        osVodigiWeb6xTests.osVodigiWS.User_ValidateResponse osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.User_Validate(osVodigiWeb6xTests.osVodigiWS.User_ValidateRequest request) {
            return base.Channel.User_Validate(request);
        }
        
        public osVodigiWeb6xTests.osVodigiWS.UserAccount User_Validate(string username, string password) {
            osVodigiWeb6xTests.osVodigiWS.User_ValidateRequest inValue = new osVodigiWeb6xTests.osVodigiWS.User_ValidateRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.User_ValidateRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            osVodigiWeb6xTests.osVodigiWS.User_ValidateResponse retVal = ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).User_Validate(inValue);
            return retVal.Body.User_ValidateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.User_ValidateResponse> osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap.User_ValidateAsync(osVodigiWeb6xTests.osVodigiWS.User_ValidateRequest request) {
            return base.Channel.User_ValidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<osVodigiWeb6xTests.osVodigiWS.User_ValidateResponse> User_ValidateAsync(string username, string password) {
            osVodigiWeb6xTests.osVodigiWS.User_ValidateRequest inValue = new osVodigiWeb6xTests.osVodigiWS.User_ValidateRequest();
            inValue.Body = new osVodigiWeb6xTests.osVodigiWS.User_ValidateRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((osVodigiWeb6xTests.osVodigiWS.osVodigiServiceSoap)(this)).User_ValidateAsync(inValue);
        }
    }
}
